version: "2"

volumes:
  assets:
    external: false
  db-data:
    external: false

services:
  https-portal:
    build: ./https-portal/
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'www.abhinavnepal.com -> http://dockerhost:3000, abhinavnepal.com => www.abhinavnepal.com'
      STAGE: 'production'
    volumes:
      - assets:/usr/share/nginx/html
  prod_db:
    image: postgres:9.6-alpine
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  prod_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - prod_db
      - https-portal
    volumes:
      - assets:/usr/share/nginx/html
