version: "2"

services:
  prod_db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
  prod_app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - prod_db
    env_file:
      - .env.prod

volumes:
  db-data:
