FROM ruby:2.3.1

# install system libraries
RUN apt-get update -yqq \
  && apt-get install -yqq build-essential libpq-dev nodejs qt5-default \
  && apt-get -q clean \
  && rm -rf /var/lib/apt/lists

# install gems
WORKDIR /usr/src/app
COPY Gemfile* ./
RUN bundle install
COPY . .

# set rails to run in production
ENV RAILS_ENV production
# precompile Rails assets. We set a dummy secret key
RUN rails SECRET_KEY_BASE=pickasecuretoken assets:precompile

CMD script/start
