version: "2"

volumes:
  assets:
    external: false
  configs:
    external: false
  db-data:
    external: false

services:
  webserver:
    image: "nginx:1.11.8"
    env_file:
      - .env.prod
    ports:
      - "80:80"
      - "443:433"
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d
  prod_db:
    image: postgres:9.6-alpine
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  prod_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d
    depends_on:
      - prod_db
      - webserver
