version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  redis:
    image: redis:6.0-alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env.local

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
    env_file:
      - .env.local
