version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.local
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.local
