---
:concurrency: 5
:queues:
  - critical
  - default
  - low
  - mailers

:schedule:
  ScholarDigestJob:
    description: "Send digest email to notify admins about scholars awaiting review"
    cron: "0 7 * * 4" # every thursday at 7am
